### ISSUE TITLE
CSS lint

### ISSUE THREAD

**Issue by Mottie** [JasonBarnabe/stylish-chrome#109]
This isn't a huge deal, but in the style editor, there are some CodeMirror css lint errors for svg's `fill` & `stroke`:

![2015-05-06 15_23_11-edit style github dark](https://cloud.githubusercontent.com/assets/136959/7502883/daa75c24-f404-11e4-90fc-97b552625655.png)

And maybe keep an eye out for [`position:sticky`](http://caniuse.com/#feat=css-sticky) which is still experimental and currently only works in Firefox & Safari.

**Comment by tophf** [comment]
CSSLint maintainer doesn't want to add these properties until he has time to make stuff configurable ([one](https://github.com/CSSLint/parser-lib/pull/97), [two](https://github.com/CSSLint/parser-lib/issues/28)). However, I think we may just use these PRs and assemble our custom CSSLint, I'll look into it.
