### ISSUE TITLE
List of installed styles not sorted in Opera

### ISSUE THREAD

**Issue by armordecai** [JasonBarnabe/stylish-chrome#13]
On the "manage installed styles" page, the list of styles is sorted by name in Firefox, but sorted by install date in Opera (currently using version 24 developer preview). Ideally they would be sorted by name in both browsers, since managing lots of styles when they're listed in what amounts to a random order is not so much fun. :smile:

**Comment by JasonBarnabe** [comment]
https://github.com/JasonBarnabe/stylish-chrome/commit/e5d50b02e73867a6b30ab27a5b6d0db8abfce663
