### ISSUE TITLE
Switching tabs sometimes disables styles?

### ISSUE THREAD

**Issue by Baegus** [JasonBarnabe/stylish-chrome#135]
I'm not really sure what's happening, but I have some CSS for YouTube that works perfectly, but sometimes when I switch to another tab and come back to YouTube, the style is not applied (even though it's enabled in Stylish).
Disabling and re-enabling the styles solves this issue.

**Comment by tophf** [comment]
Does it happen with the master branch? There were a lot of changes since the last published release.

**Comment by Baegus** [comment]
I'll try updating to master.

**Comment by tophf** [comment]
Fixed in v1.4. The issue should be closed.
