### ISSUE TITLE
Sometimes stylish will activate styles at random for pages it's not supposed to activate

### ISSUE THREAD

**Issue by dumpsters** [JasonBarnabe/stylish-chrome#137]
First off I have no idea how to reproduce this since it just happens at random.

Here is the following website: https://gamesdonequick.com/schedule

### How it's supposed to look:
![supposed](http://i.imgur.com/omBiqWD.png)

### How it looks when the bug happen:
![bug](http://i.imgur.com/upDj6hU.png)

As you can see even when the bug happens you don't see a [1] in the stylish icon.
One of the styles I have use that same color for links and background so I think that's the one "leaking" into other pages but I don't know why really. Anyway here's kinda how the code goes: http://pastebin.com/raw.php?i=jrm5Kxt4.

### Another bug I've noticed is that sometimes styles will:
- **Not work** happened with https://userstyles.org/styles/101409/ and my style
- **Work but when you go back to the tab it will be deactivated or partly working** (some areas will still have the original style) happened with https://userstyles.org/styles/101409/ and my style.
- **Work partially** (some areas will still have the original style and deactivating and activating the style will fix it) happened with https://userstyles.org/styles/101409/ and my style.

Using Windows 7, Chrome Beta x64 and latest Stylish from the chrome store.

**Comment by tophf** [comment]
This could have been fixed in the master branch as it has a lot of changes since the latest official release. Can you try it?
