### ISSUE TITLE
Original content is flickering before stylish applies the user style

### ISSUE THREAD

**Issue by tophf** [JasonBarnabe/stylish-chrome#15]
Styles that fully change the appearance of websites (light -> dark, stuff repositioning, etc) are unusable in webkit based browsers because there is a noticeable delay before the user style is applied after the original unstyled page is shown (1/4 - 1/2s on a complex page).

I don't know if it's possible at all, but maybe AdBlock's implementation could be helpful? Or Chrome's [Content Scripts](https://developer.chrome.com/extensions/content_scripts) mechanism? [chrome.webNavigation API](https://developer.chrome.com/extensions/webNavigation#event-onCommitted) where maybe a  DOM observer/on-the-fly-content-modifier could be injected?

**Comment by JasonBarnabe** [comment]
Finally got around to investigating this. Tested with two simple styles installed, applying to a local file, with 10 repetitions.

The code as is takes an average of 121ms from the time the content script starts until after the style gets applied. There is a noticable flicker.

Looking at the content script, two messages are needed to the background process: one to get a list of styles to apply, then another to get which sections of those styles to apply. I reworked the script to only do one message. This reduced the time required to an average of 71ms, but the flicker remains.

Breaking down what exactly's taking so long, I see the following timings:
- Start of content script to background script receiving message - 56ms
- Background script receiving message to background script ready to reply (loading the styles) - 13ms
- Background script ready to reply to background script replied - 6ms
- Background script replied to content script received response - 43ms
- Content script received response to styles added to DOM - 5ms

So the majority of the time is actually waiting for the messages to go back and forth.

Looking into `chrome.webNavigation.onCommitted`, it runs on average 10ms *before* the content script starts. Sending a message from the background script to the tab with the styles to apply, it beats the previous method by an average of 40ms, and the flicker is gone. I will investigate this further to see if it's a suitable method.

**Comment by JasonBarnabe** [comment]
The first problem with `onCommitted` is that it can run before the content script adds its listeners. I can:

- Try to detect if the content script is ready
- Send the message more than once
- Use `insertCss` instead (Will this be available if the content script isn't? Can a style added this way be removed?)
- Use executeScript instead (Will this be available?)

**Comment by JasonBarnabe** [comment]
`executeScript` seems reliable, but is actually slower than sending a message to the content script, so there's still flicker.

**Comment by JasonBarnabe** [comment]
I think what I'll do is keep the existing arch (content script asks for styles, gets reply, and applies) but also add the background script sending messages to tabs on `onCommitted` with the styles to apply. That way, when `onCommitted` works, you get flicker-less loading. When it doesn't, the old reliable method fires.

So far with testing, the only times I've found the `onCommitted` approach not to work is when you go back to a page.

**Comment by tophf** [comment]
This is awesome!

> So far with testing, the only times I've found the onCommitted approach not to work is when you go back to a page.

Indeed, Chrome may keep the loaded page in memory and pull it instantaneously, but maybe other events like onTabReplaced, onHistoryStateUpdated, onBeforeNavigate still fire?

**Comment by JasonBarnabe** [comment]
The event still fires, it just fires before the content script is ready to receive its message.

**Comment by tophf** [comment]
Fixed.
