### ISSUE TITLE
Middle-click on link is apply style from linked site

### ISSUE THREAD

**Issue by Mottie** [JasonBarnabe/stylish-chrome#151]
We have a GitHub-Dark style which limits itself to [GitHub related sites](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L1):

```css
@-moz-document
    regexp("^https?://((gist|guides|help|raw|status|developer)\.)?github\.com((?!generated_pages\/preview).)*$"),
    domain("render.githubusercontent.com"),
    domain("raw.githubusercontent.com") {
    ...
}
```

But today while using Twitter (which I hardly ever use), I middle clicked on a link to take me to GitHub. Stylish applied the GitHub theme to the Twitter page

![twitter-with-github-dark](https://cloud.githubusercontent.com/assets/136959/9665263/b026cba4-5234-11e5-8878-b3df7c848fb7.gif)

What's even stranger, is if I middle-click on the link, then close the GitHub styled Twitter page, the GitHub page I just opened remains unstyled.

**Comment by vsemozhetbyt** [comment]
Here is the same bug and related discussing:

https://forum.userstyles.org/discussion/46834/strange-bug-in-the-stylish-for-chrome

**Comment by Mottie** [comment]
Oh, oops, I didn't realize it was already reported.

**Comment by vsemozhetbyt** [comment]
It is fixed in current state, but you will need development mode to install it.

https://forum.userstyles.org/discussion/46871/stylish-for-chrome-1-4-0b1

**Comment by Mottie** [comment]
Ok, thanks... Duplicate of #137.
