### ISSUE TITLE
Stylish leaking to other pages. 

### ISSUE THREAD

**Issue by rlemon** [JasonBarnabe/stylish-chrome#152]
I have the github dark stylish theme. 

Here is what it matches:

URLs on Domain: 
render.githubusercontent.com
raw.githubusercontent.com

URLs matching the regexp: 
^https?://((gist|guides|help|raw|status|developer).)?github.com((?!generated_pages/preview).)*$

problem is this style is leaking to other tabs. I switch back to a given tab and the style is injected incorrectly. I haven't been able to figure out the trigger yet (happened a few dozen times today, stackoverflow.com and some random blogs have been affected), and I wouldn't even begin to know where to look to see what is causing this. The issue does correct itself once I refresh the page. 

I know this is a vague bug report, so any tips on what you would need from me would be great.

**Comment by vsemozhetbyt** [comment]
Please, read this with comments:

https://github.com/JasonBarnabe/stylish-chrome/issues/151

**Comment by tophf** [comment]
Fixed in v1.4. The issue should be closed.
