### ISSUE TITLE
Userstyles periodically "vanish" from TweetDeck

### ISSUE THREAD

**Issue by YellowAfterlife** [JasonBarnabe/stylish-chrome#153]
I have [this small userstyle](https://gist.github.com/YellowAfterlife/36b7b379eb8d67eda38a) (via [generator](http://yellowafterlife.itch.io/swickdeck)) that applies to [TweetDeck](https://tweetdeck.twitter.com/) and alters some colors/layout. Nothing particular.
What is odd, however, that time to time (without any particular perquisites, but seemingly on switching tabs) the style "unapplies" -- technically speaking, the `<style>` element simply vanishes from the page. At such times, Stylish keeps thinking that the style is in place, and toggling the style off and back on restores it until the next time:
![gif](https://cloud.githubusercontent.com/assets/731492/9908722/9e3e12c6-5c9d-11e5-8c7b-16c0ff9f1144.gif)
This started happening somewhat recently (1-2 weeks ago).
I have had someone else confirm that userstyles disappear for them as well on TD.
Does not occur on the Firefox version of Stylish (with about the same set of plugins and userstyles).

**Comment by tophf** [comment]
Fixed in the beta.

**Comment by tophf** [comment]
Fixed in v1.4. The issue should be closed.
