### ISSUE TITLE
support pref syncing via chrome.storage.sync

### ISSUE THREAD

**Issue by vapier** [JasonBarnabe/stylish-chrome#156]
when switching to a diff system/profile, i have to reload all my settings by hand.  Chrome syncs all my extensions already, so when i log into a new session, it'd be nice to have all of stylish stuff follow me.

can you add an option (on by default?) to sync localStorage to chrome.storage.sync ?  localStorage provides synchronous access while chrome.storage.* does not, so probably want to do something like:
(1) at install time, seed localStorage with chrome.storage.sync settings
(2) whenever a setting is updated, save it to chrome.storage.sync

**Comment by tophf** [comment]
localStorage contains these settings:

![screenshot](https://cloud.githubusercontent.com/assets/1310400/10267665/94f41308-6aa5-11e5-8bb8-adfd8d701e3f.png)

Making them sync is easy indeed. However if you talk about styles it's a different story: #2

**Comment by docrinehart** [comment]
Bump! I would like to see this merged!
