### ISSUE TITLE
[Bug] Entire extension crashes and gets corrupted when visiting its URL without "manage.html".

### ISSUE THREAD

**Issue by katacarbix** [JasonBarnabe/stylish-chrome#158]
Here are the steps to reproduce it:

1. Go to Stylish's options page, one way or another.
2. In the address bar, remove "manage.html" from the end and press enter.
3. Page will close. Go to Extensions manager and see message telling you "this extension may have been corrupted".

This happened to me because I thought it would take me back to the main page from where I was. I'm not sure if this is a Chrome issue or extension-specific.

**Comment by tophf** [comment]
Can't reproduce any of the symptoms on Chrome 48 and 45. Chrome immediately reports there's no such page URL.

Try the usual: create an empty new Chrome user profile and don't forget to reset chrome://flags

![clip225-fs8](https://cloud.githubusercontent.com/assets/1310400/10645311/ce499cd4-7835-11e5-83b5-739831c04957.png)

**Comment by katacarbix** [comment]
Ok, sorry about that

**Comment by katacarbix** [comment]
You're right, it was a problem with the computer I was using.
