### ISSUE TITLE
Styles sometimes don't apply

### ISSUE THREAD

**Issue by acbeers** [JasonBarnabe/stylish-chrome#162]
I have a simple locally-authored style against outlook 365.  sometimes, the styles don't apply.  My style is checked in the menu, and if i uncheck and recheck the box then the styles do apply.

I notice this most often when outlook decides it needs to re-authenticate, and so goes through a series of redirects to complete that authentication.  When it arrives back in the main (mail) interface, the styles aren't applied.

**Comment by tophf** [comment]
We'll need to see the style, otherwise we can't help you.

**Comment by acbeers** [comment]
Here is the exported style:

@-moz-document url-prefix("https://outlook.office.com/owa/?realm=tableau.com#path=/mail"), url-prefix("https://outlook.office365.com/owa/?realm=tableau.com#path=/mail") {
/* Reduce padding between elements of the message list */
._lvv_M {padding-top: 2px; }
._lvv_P { margin-top: 0px; }
._lvv_U { margin-top: 0px; }

/* Shorter message height */
._lvv_B._lvv_C {
    height: 65px;
    border-bottom: 1px dotted lightgray;
}

/* Background on unread messages to make them stand out */
:not([aria-selected="true"]) > [aria-label~="Unread,"] {
    background-color: #f7fff7;
}

/* This appears to be section headers in the message list */
._lvv_91 { line-height: 12px; }
._lvv_a1 { background-color: #f0f0f0; }

/* Folder list on the side */
._n_r5._n_f5 { height: 21px }
._n_k5 { vertical-align: top }
._n_o5 { padding-top: 2px; height: 21px; top: 0px; }
._n_m5 { vertical-align: top }
}

**Comment by tophf** [comment]
I don't have an MS account so I can't test it. What I see is that the style section has `#` which means that the page is dynamically updated without being fully reloaded. Stylish-chrome supports this feature.

What version of Chrome and Stylish are you using?

**Comment by acbeers** [comment]
Chrome: Version 47.0.2526.106 (64-bit)
Stylish: 1.4.0

**Comment by tophf** [comment]
Looks okay.

Did the style work before on another version of Chrome?

**Comment by acbeers** [comment]
Don't know - installed Stylish 2 days ago, so I'm new to the party :)

**Comment by tophf** [comment]
Unless someone comes up with a better idea I suggest using a less restrictive URL prefix like `https://outlook.office.com/owa/`.

**Comment by acbeers** [comment]
I'm open to trying that out - would be a shame to drop the end, since that limits the styles to mail.  Odd things, though - when I've noticed the problem, the URL matched, and the stylish icon had a (1) on it, meaning it thought that the style was applying.

**Comment by JasonBarnabe** [comment]
I imagine this could be caused by navigation that just changes the hash in the URL and loads it with JS.

**Comment by tophf** [comment]
Well, that could the case as MS is known to disregard the standards.

@acbeers, try finding a mail-specific HTML element that you can utilize to narrow down the CSS selectors.

**Comment by acbeers** [comment]
Ok, found a repro.  If I go to office 365, switch to the calendar view, reload at that point, then switch back to mail, the styles aren't applied.  The switch to mail is done without a page reload, but the URL is updated after the #.
