### ISSUE TITLE
Stop using Web SQL

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/stylish-chrome#167]
Web SQL is deprecated and doesn't work in Firefox. Move to something else, like IndexedDB.

**Comment by tophf** [comment]
IndexedDB is still reportedly slower than WebSQL according to a few tests I've seen. However for the needs of Stylish the difference might be negligible. Anyway it should be tested first in order not to make Stylish-chrome slower.

**Comment by JasonBarnabe** [comment]
I imagine it wouldn't be significant, especially considering Stylish is currently converting the result of the WebSQL into a JS object, while with IndexedDB this would not be necessary. In any case, Web SQL is likely going to go away even in Chrome at some point in the future, so sticking with it isn't an option.

Are you willing to work on this? I don't want to duplicate effort. The solution should include migration from the current storage.

**Comment by JasonBarnabe** [comment]
I've added this. The WebSQL data will get converted automatically, but not deleted. To wipe out the new DB (and re-run the migration), run this from the console:

```js
indexedDB.deleteDatabase("stylish")
```
