### ISSUE TITLE
chrome-extension:// not supported?

### ISSUE THREAD

**Issue by zizhengwu** [JasonBarnabe/stylish-chrome#170]
Hi, I have checked "allow access to file URLs", however, stylish doesn't seem to be working on chrome-extension://. 

Could you confirm that this is a limitation of Stylish or I wrote the styles wrong?

**Comment by tophf** [comment]
Chrome doesn't allow extensions to inject into other extension's pages.

**Comment by tophf** [comment]
You can only style Stylish's [own pages](https://userstyles.org/styles/browse/chrome-extension) like Manage or Editor or Popup.

**Comment by zizhengwu** [comment]
Hi @tophf, thank you so much for your confirmation. I was wondering is there a way to edit the styles of a chrome extension. By now I could only accomplish that by the developer tools (F12) provided by Chrome every time I open the extension. Is there a workaround?

**Comment by zizhengwu** [comment]
By the way, I actually want to inject styles to a Chrome app.

**Comment by tophf** [comment]
I guess you can only unpack the app somewhere, edit its files, then drag'n'drop its folder onto an open `chrome://extensions` page to install it locally. But there are drawbacks: it won't be autoupdated and each time you start Chrome on Windows you'll either have to click 'Cancel' in the warning popup or use a [dll patch](http://stackoverflow.com/a/30361260/3959875) (after each Chrome update).

**Comment by zizhengwu** [comment]
Got it, thanks!
