### ISSUE TITLE
page loads slower with the extension enabled

### ISSUE THREAD

**Issue by ghost** [JasonBarnabe/stylish-chrome#171]
1. create a style that applies to all pages
2. navigate to https://kangax.github.io/compat-table/es6/

with stylish enabled it takes ~7.1 seconds for the page's DOMContentLoaded event to fire 
with stylish disabled it takes ~4.7 seconds

measured using chrome dev tools' network tab with all other extensions disabled

i think its related to the mutation observer or the dynamic iframe thing in ./apply.js

**Comment by tophf** [comment]
Doesn't happen on current master branch (both scenarios finish in ~3 seconds here), fixed by #165

**Comment by 18763C27** [comment]
oh

i'm using the version from the chrome web store

it doesn't have your fixes in it

**Comment by 18763C27** [comment]
um

who do i contact to have [the version on the chrome web store](https://chrome.google.com/webstore/detail/fjnbnpbmkenffdnngjfgmeleoegfcffe) updated

or should i open a new issue here

:?

**Comment by JonasNo** [comment]
Perhaps he have notifications off on github so go here:
https://forum.userstyles.org/discussion/47242/the-future-of-stylish-for-firefox

or here:
https://forum.userstyles.org/categories/style-development

**Comment by JasonBarnabe** [comment]
I assume this is no longer an issue.
