### ISSUE TITLE
Style Manager reports 'Update completed', but style isn't updated

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/stylish-chrome#172]
in re: https://forum.userstyles.org/discussion/49688/chrome-my-userstyle-wont-get-updated

The immediate problem is that `doUpdate()` is [passing a message without a callback](https://github.com/JasonBarnabe/stylish-chrome/blob/master/manage.js#L363).

The underlying problem is that Chrome passes a "throw error" function when the message doesn't have a callback, and saveStyle() [doesn't distinguish Chrome's callback from Stylish's callbacks](https://github.com/JasonBarnabe/stylish-chrome/blob/master/storage.js#L149).

The problem underlying that is that saveStyle() [changes the extension state in  `request.onsuccess`](https://github.com/JasonBarnabe/stylish-chrome/blob/master/storage.js#L111) instead of in `transaction.oncomplete`. The `put` request succeeded but the transaction failed when the message handler threw, so the UI was updated even though the database wasn't.

(I hate IndexedDB.)

**Comment by kmark** [comment]
Does this bug prevent the style from actually being updated or just prevents the report of a successful update? If it's the former it'd be awesome to have a new release on the Chrome Web Store since this looks like a show stopper.

**Comment by hideheader** [comment]
How exactly does it stop the show?

**Comment by kmark** [comment]
My understanding is that this prevents updates entirely, yes? Not being able to update styles once installed seems like a relatively major bug.

**Comment by hideheader** [comment]
Mmm, no. You can update a style from the style page on userstyles.org. You can't update a style from the Style Manager page in Stylish for Chrome. I agree, the fix should have been pushed to the Chrome store before now, but that's not a show stopper - in fact, few people have noticed this bug at all.

In the meantime, you can disable production Stylish and install patchy Stylish from here as an unpacked extensions. Replace patchy Stylish's database folder with a hard link to production Stylish's database folder to continue using your existing styles.

**Comment by kmark** [comment]
Ah okay, thanks for the clarification. I'm surprised few people have noticed, I'm guessing they either don't know that the styles aren't updating or the majority of people prefer to update their styles from the website. Thanks again for the patchy instructions.

**Comment by AlecRust** [comment]
Not sure why this is closed? Neither the sidebar "Check all styles for updates" button or the "Check for update" button by each style works, though they look like they do.

![screencast](http://g.recordit.co/iEsyvQ083Z.gif)

**Comment by tophf** [comment]
>Not sure why this is closed?

Because here it was fixed in #173
