### ISSUE TITLE
Enabling a style overwrites 'Add Style' content with enabled style

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/stylish-chrome#174]
https://forum.userstyles.org/discussion/49999/bug-chrome-unsaved-style-erased-after-loading-different-style-for-same-domain

**Comment by JasonBarnabe** [comment]
The edit page is supposed to reload if the style is edited by some external force. The check was not happening correctly.

Your PR is essentially correct, but I've added a condition that the styleId must be set (i.e. this is an existing style) for this to happen.
