### ISSUE TITLE
[Bug] Styles update won't save

### ISSUE THREAD

**Issue by Destroyer** [JasonBarnabe/stylish-chrome#177]
I've encountered bug where updates to styles are not saved. 
Steps:
1. find outdated style
2. install update
3. close the stylish tab
4. open it again and check for updates of that same style

I'm using Chrome 51.0.2704.79 m (64-bit)

**Comment by hideheader** [comment]
#172

**Comment by hideheader** [comment]
Corrected and closed as #172
