### ISSUE TITLE
Ability to paste full style, unprefixed @document

### ISSUE THREAD

**Issue by silverwind** [JasonBarnabe/stylish-chrome#31]
One thing that bothers me quite a bit about developing for Stylish on non-Firefox is that you have to unwrap the `@-moz-document` rules after pasting in a Style from an external editor.

I'd envision unprefixed `@document` rules which could be recognized by engines other than Firefox. It would make using an external editor and updating an stylesheet much more bearable for Chrome. While unprefixed `@document` isn't a standard yet, it probably will be at some time in the future, so the keyword would be pretty safe to use I think.

https://developer.mozilla.org/en-US/docs/Web/CSS/@document

**Comment by JasonBarnabe** [comment]
This would be good. The difficulty of course is you'd be writing a CSS parser to accomplish it.

**Comment by silverwind** [comment]
Yeah, getting this right may be quite hard. I assume a style can include multiple `@document` rules and the probably can be nested too, right?

**Comment by JasonBarnabe** [comment]
Yup.

**Comment by tophf** [comment]
What about implementing the simplest form which is used by 99.999% of all styles - a sequential non-nested list?

**Comment by tophf** [comment]
@JasonBarnabe, maybe you can use my [implementation](https://github.com/tophf/stylish-chrome/commit/4c90376) and refactor it or should I open a PR as is?

**Comment by JasonBarnabe** [comment]
I would really prefer a real parser here. I've gone the regexp route before on userstyles.org and it ends up mangling stuff.

userstyles.org uses a Ruby library for CSS parser, so no, I don't see how you could reuse that here.

**Comment by silverwind** [comment]
I think rework's css parser could be of use here. I'll experiment with it. It even lists support for `@document`:

https://github.com/reworkcss/css#document

**Comment by silverwind** [comment]
That module looks workable at first glance. The only open question to me is, if we want to retain the current inputs and buttons below the editor. I think they should be dropped with this.

**Comment by JasonBarnabe** [comment]
Yes, it should be one code box, just like in Firefox.

Note that this is a pretty massive change and I probably won't include it in the next release. But if we can get it done and extensively tested, it could go in the release after that.

**Comment by tophf** [comment]
I strongly disagree. Sectioned display is by far more readable and well-organized. If there is any bad thing about Stylish-Firefox's editor it's actually the lack of sections.

**Comment by JasonBarnabe** [comment]
Could allow for both modes, I guess. The code's gotta get chopped up and put back together regardless.

**Comment by silverwind** [comment]
@tophf you can still lay out a @document rule in a readable manner:

````
@document url(http://www.w3.org/),
          url-prefix(http://www.w3.org/Style/),
          domain(mozilla.org),
          regexp("https:.*") {
          
}
````

Also, nesting enables a lot of flexibilty.

**Comment by tophf** [comment]
1. The overall layout won't be readable whereas with sections it's instantly obvious
2. Indeed, but it's needed in like what - 1% of cases?

**Comment by tophf** [comment]
Why don't we add meanwhile [the regexp implementation](https://github.com/tophf/stylish-chrome/commit/80a7e5ed4758ab9b59a1da13d16552eb3b736d17) which will work in almost all cases and display a warning "please, simplify the style structure" otherwise?

**Comment by tophf** [comment]
Or maybe do it via userstyles.org via adding a new API to the site that accepts a mozilla-formatted style and sends back a json-formatted response?
