### ISSUE TITLE
"Update all styles" button

### ISSUE THREAD

**Issue by Baegus** [JasonBarnabe/stylish-chrome#36]
I think there should be a button for updating all styles (it would appear after checking all styles for updates).
When you check all styles for updates now, you still need to manually click the "Install update" button for each style.

**Comment by JasonBarnabe** [comment]
Make sense, except "Update all styles" is misleading. Maybe "Apply all updates" instead?

It should appear only if there are updates to install, and after clicking, should be replaced by text like "All updates applied."

**Comment by Baegus** [comment]
That's exactly what I was thinking of.
