### ISSUE TITLE
Match `url-prefix()`, not `url()`, on "this URL"

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/stylish-chrome#42]
Yeah, I know, the label won't be strictly correct but `url-prefix()` is usually what you want. The change is functionally indistinguishable for most true `url()` match expressions. When you do want `url-prefix` (which is almost always) the `SELECT` dropdown is already correct, sparing you a small but continually irritating step.

Were it practical I'd display the whole URL path and let a click determine the end of the `url-prefix()`. (Maybe with a really wide menu on a really wide display.)

**Comment by JasonBarnabe** [comment]
I see how you would want it just to be able to handle query strings and fragments, but other times it would end up affecting stuff you may not have intended. For example, for https://greasyfork.org/en/scripts you'd probably want https://greasyfork.org/en/scripts?page=2 in there too, but not https://greasyfork.org/en/scripts/1317-download-youtube-videos-as-mp4

**Comment by hideheader** [comment]
Confused. I'm proposing only that "this URL" create `@document url-prefix(documentURI) {}` instead of `@document url(documentURI) {}`. I'm not suggesting any auto-magical transformations. I'll still have to edit the argument value most of the time, but at least the `SELECT` value will be right. The only loser in this change is the guy who really does want `url(https://greasyfork.org/en/scripts)` - how often does that happen, anyway?

**Comment by tophf** [comment]
> how often does that happen, anyway?

Nobody knows.

However it'd be reasonable to have a menu item for url-prefix like this:
Write style for........ **this URL and below**.

**Comment by hideheader** [comment]
> Nobody knows.
Everyone knows:
````sql
SELECT COUNT() FROM (
  SELECT section_meta.value, section_meta.section_id, sections.style_id
    FROM section_meta JOIN sections ON sections.id = section_meta.section_id
    WHERE section_meta.name="url"
    GROUP BY sections.style_id
)
````
out of 
````SQL
SELECT COUNT() FROM styles
````
About 1.1% (n=215).
