### ISSUE TITLE
Update CodeMirror to 4.13+

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/stylish-chrome#43]
"Make the CSS mode understand some modern CSS extensions." (Including `@document`.)
https://github.com/codemirror/CodeMirror/blob/4.13.0/mode/css/css.js#L160

**Comment by JasonBarnabe** [comment]
Full circle: https://bugzilla.mozilla.org/show_bug.cgi?id=977665

**Comment by hideheader** [comment]
So that's "yes" to updating CodeMirror, then?

**Comment by JasonBarnabe** [comment]
Yeah. Maybe jump up to 5 though?

**Comment by hideheader** [comment]
I see that 4.13 and 5.0 were both released on the same day, and my Spidey sense starts tingling. Is 5.0 just 4.13 + mobile + contentEditable? That would be fine.

**Comment by hideheader** [comment]
The [CodeMirror demos](http://codemirror.net/demo/) are using 5.0.1; `buffers`, `closebrackets`, `closetag`, `folding`, `html5complete`, `indentwrap`, `lint`, `marker`, `markselection`, `matchhighlighter`, `merge`, `resize`, `search`, `visibletabs`, `widget`, `xmlcomplete` work as they did.
