### ISSUE TITLE
Suggestion: edit style in a panel

### ISSUE THREAD

**Issue by tophf** [JasonBarnabe/stylish-chrome#47]
Chrome has a yet experimental API to open windows as panels, enabled via chrome://flags/#enable-panels flag.

>Enable Panel windows that open outside of the browser frame.
>Attempts to open a Panel will open a popup instead if not enabled. 
>Panels are always enabled on the dev and canary channels.

It looks nice and so far I like it much more than a new tab or a new window. Of course, using this by default for everyone would be wrong as the API may be removed even though it's been present for several years iirc.

So... maybe an option "Open in panel" with a link to that flag and a prompt to enable it?

P.S. The diff:
```diff
--- a/popup.js
+++ b/popup.js
@@ -123,7 +123,7 @@ function getId(event) {
 function openLinkInTabOrWindow(event) {
 	event.preventDefault();
 	if (localStorage['openEditInWindow'] == 'true') {
-		chrome.windows.create({url: event.target.href});
+		chrome.windows.create({url: event.target.href, type: 'panel', focused: true});
 	} else {
 		chrome.tabs.create({url: event.target.href});
 	}
```

So should I implement it and submit a PR?

**Comment by JasonBarnabe** [comment]
What does a panel do, exactly? Is it just a window with less chrome?

Can you detect if this is enabled?

**Comment by tophf** [comment]
1. An always-on-top minimally decorated window that opens in the corner, near the notification tray, on Windows at least
2. Yup, no addressbar, no tabs, devtools, etc
3. I don't think so

![example 1](https://cloud.githubusercontent.com/assets/1310400/6478344/05c085f6-c242-11e4-93de-93d0ce2da191.png)

[example 2](https://lh4.googleusercontent.com/OzPGsVNI3xndC3gX5sjxdRFKDw7zrJyxgXp6RVN4YQlsh88Sndzbl23jY4vumTzj0njFp-uRFw=s640-h400-e365-rw)
[example 3](https://lh4.googleusercontent.com/rCshq8NM8EG0-KkYtpNu6VG3w8kzhsiMmmIbjpHzot6-bTHTpne7cakFZLN9ae_vaW-7AZn6fPM=s640-h400-e365-rw)

**Comment by JasonBarnabe** [comment]
I'm unsure if this is useful as it doesn't seem to work even with the flag enabled here on Linux. The `create` call throws an exception.

**Comment by tophf** [comment]
The primary goal was not the panel mode per se, but to open the edit window that won't cover the original page which is a horrible issue with Stylish-Chrome. So a universally working solution would be to remember the detached window position in some kind of "onMove" event and automatically restore it next time.

**Comment by JasonBarnabe** [comment]
That's what it does already...? (assuming you open from the popup)

**Comment by JasonBarnabe** [comment]
Oh, nevermind. You're talking about the size and position of the window rather simply the fact that it is its own window.
