### ISSUE TITLE
lint warnings are still showing

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/stylish-chrome#51]
lint warnings are useless. I tried to get rid of them but I still see the yellow squiggles.

**Comment by hideheader** [comment]
There's also this; I don't know what the ramifications are.

![eval-throws](https://cloud.githubusercontent.com/assets/10900909/6540964/f374a3b8-c486-11e4-929c-619b627f13ed.png)
![eval-code](https://cloud.githubusercontent.com/assets/10900909/6540972/316c5efe-c487-11e4-92d1-3c820728fd58.png)

**Comment by tophf** [comment]
> the yellow squiggles

```css
.CodeMirror-lint-mark-warning {
  background: none;
}
```

**Comment by tophf** [comment]
@hideheader commented on [Mar 7, 2015, 1:02 PM GMT+3](https://github.com/JasonBarnabe/stylish-chrome/issues/51#issuecomment-77682318 "2015-03-07T10:02:57Z - Replied by Github Comment Enhancer"):
> There's also this; I don't know what the ramifications are.
> 
> [![eval-throws](https://cloud.githubusercontent.com/assets/10900909/6540964/f374a3b8-c486-11e4-929c-619b627f13ed.png)](https://cloud.githubusercontent.com/assets/10900909/6540964/f374a3b8-c486-11e4-929c-619b627f13ed.png)  
> 
> [![eval-code](https://cloud.githubusercontent.com/assets/10900909/6540972/316c5efe-c487-11e4-92d1-3c820728fd58.png)](https://cloud.githubusercontent.com/assets/10900909/6540972/316c5efe-c487-11e4-92d1-3c820728fd58.png)

Happens on quoted strings here too. I think CSS don't need lint inside strings, so what about we simply delete this eval from CSSLint entirely? The alternative is adding `'unsafe-eval'` to `content_security_policy` in manifest.json, which might be a security risk and needs rtfming/testing.
