### ISSUE TITLE
Add a `keyMap` for Windows defaults

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/stylish-chrome#56]
And some means to apply it. Most of your users ([80%](http://www.w3schools.com/browsers/browsers_os.asp) - [90%](http://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers)) probably use Windows, so this should be the default `keyMap` if a platform-specific assignment can't be made.

**Comment by tophf** [comment]
CodeMirror has a [built-in platform-specific](https://github.com/JasonBarnabe/stylish-chrome/blob/51a9c5c016a8c700ef6b4a841ae0790610d9c369/codemirror/lib/codemirror.js#L5566-5604) pc/mac keymap and it seems sufficient for Stylish, right? 

And BTW, unless an option is introduced to select CodeMirror's advanced keymaps (vim/emacs/sublime), the keymaps/ directory could be removed as it's unused currently.

**Comment by hideheader** [comment]
1. `pcDefault` isn't a set of Windows shortcuts. For example, 'find next' is F3 in Windows and Ctrl+G is 'goto line', not 'find next'.
2. There is no way for a user to select a `keyMap` in Stylish today.
