### ISSUE TITLE
Suppress Chrome's 'Find' in the editor

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/stylish-chrome#72]
Chrome's Find searches CodeMirror's edit buffer independently of CodeMirror and highlights matches it finds there. Worse, its highlighting is close to that of CodeMirror, so it's more difficult to sort out which is which than it was in FIrefox.
![chrome-vs-codemirror](https://cloud.githubusercontent.com/assets/10900909/6653277/5e135c98-ca61-11e4-9c2b-592ea52edf9a.png)

**Comment by tophf** [comment]
Yup, that's a must, along with a global text replace.

>TO DO: override Ctrl-F/F3 on the entire page, display a simple inputbox somewhere, and perform the search in code and applies-to definitions.
