### ISSUE TITLE
Migrate Options to v2

### ISSUE THREAD

**Issue by tophf** [JasonBarnabe/stylish-chrome#73]
[Documentation](https://developer.chrome.com/extensions/optionsV2)

> In a future version of Chrome, any extension which specifies options_page will change to match the options_ui behavior - most importantly, they will always be embedded in chrome://extensions - **so migrate as soon as possible**.

Currently the options page forced to v2 format looks like this:
![screenshot](https://cloud.githubusercontent.com/assets/1310400/6654146/a72554e8-cac2-11e4-9a1a-a8c1afe8db47.png)

1. The filters should be moved below the options, because uhm, the filters aren't the options that alter the extension's behavior.
2. There should be probably a link to open a new window/tab with the options, shown only for this @media-width.

---

**What about this:**

![screenshot2](https://cloud.githubusercontent.com/assets/1310400/6654184/012e574e-cac5-11e4-9585-3e242285996d.png)

---

**Or just force the options to open in a tab** like [uBlock does](https://github.com/gorhill/uBlock/blob/master/platform/chromium/options_ui.js):

manifest.json:
```js
    "options_page": "dashboard.html",
    "options_ui": {
        "page": "options_ui.html"
    },
 ```
options_ui.html:
```html
<!DOCTYPE html>
<head>
<script src="js/vapi-client.js"></script>
<script src="js/options_ui.js"></script>
<title></title>
</head>
<body>
</body>
</html>
```
options_ui.js:
```js
var messager = vAPI.messaging.channel('_open');
messager.send({
    what: 'gotoURL',
    details: {
        url: 'dashboard.html',
        index: -1
    }
});
window.close();
```
The small options window won't even be shown.

**Comment by JasonBarnabe** [comment]
What Chrome is doing makes sense if you're just using it for options, but with Stylish it's much more.

So yeah, I'd prefer faking it out so it still opens as a full-fledged document.

**Comment by tophf** [comment]
Closing it until Chrome actually enforces the V2 in Stable.
