### ISSUE TITLE
Stylish on Opera extensions directory?

### ISSUE THREAD

**Issue by YellowAfterlife** [JasonBarnabe/stylish-chrome#77]
Stylish is available in the directory of current extensions for Opera,
https://chrome.google.com/webstore/detail/fjnbnpbmkenffdnngjfgmeleoegfcffe
Understandably, current versions of Opera use Chromium so it is not a huge hassle of uploading it, but seeing no mentions of the Opera version on userstyles, my question is - is the extension authentic? Or not actually uploaded by an associated party / not to be trusted?

**Comment by JasonBarnabe** [comment]
You mean [this](https://addons.opera.com/en/extensions/details/stylish/?display=en)? This is authentic Stylish, same as on Google Web Store.

[This](https://addons.opera.com/en/extensions/details/stylish-for-opera/) is Stylish for Presto, different than the others, not written by me, but approved as the official Stylish for old Opera.

**Comment by YellowAfterlife** [comment]
> You mean this? This is authentic Stylish, same as on Google Web Store.

Yes, sorry, I have added the wrong link. That was what I meant. Thanks for responding!
