### ISSUE TITLE
'From Mozilla format' button doesn't work

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/stylish-chrome#79]
Ditto for the help icon. There's no listener on the button [figure] or the 'help' image. It's supposed to address #31, yes?

![from-mozilla-format](https://cloud.githubusercontent.com/assets/10900909/6786643/013d613a-d164-11e4-92bb-d5af745e9675.png)

**Comment by JasonBarnabe** [comment]
I must've missed this in the code review. Looks it was added by accident, and I don't want it in this version anyway.

**Comment by hideheader** [comment]
How do you "accidentally" add two controls?

**Comment by JasonBarnabe** [comment]
Adding in the feature then taking it out, but missing the controls. Copying code from another branch. Cat walks on keyboard and this is the universe where it ends up being that code.

**Comment by hideheader** [comment]
You're in a generous mood today. Why not pull #75 then and tart up the UI later?
