### ISSUE TITLE
Styles are applied, but not listed in the menu.

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/stylish-chrome#80]
Example is 'Google Graphite 2K14' applied to a new tab.

![but-it-_does_-work](https://cloud.githubusercontent.com/assets/10900909/6786680/3dd40f04-d164-11e4-8cc6-4e05a1ed3be5.png)

**Comment by JasonBarnabe** [comment]
From the perspective of `tab.url`, it's `chrome://newtab/`. From the perspective of `location.href`, it's a page on Google.

**Comment by hideheader** [comment]
Whatever the "perspective", it's a style applied to the page which isn't listed for the page and can't be disabled from the page.

**Comment by JasonBarnabe** [comment]
Yeah, I know, just providing some data.

I don't see any `tab.whatUrlAreYouReally`. Maybe adding a content script to perform this function is the only way to go.

**Comment by JasonBarnabe** [comment]
Seems to work fine with that.

**Comment by hideheader** [comment]
Really the whole business of styling exogenous `IFRAME`s should be revisited. Usually it's unwanted, as in the Google analytics frame or (usually) the social media buttons. Here it seems to work OK even though the page layout isn't that of Google Search, but that could well be Anton doing something clever. The social media buttons are similar cases to this one - *i.e.*, you don't want to style the Tumblr button with the Tumblr dashboard theme, and if someone should style the button you probably don't want that as your dash theme, so it would be best if somehow the style could "know" whether it's in a frame or not.

**Comment by JasonBarnabe** [comment]
This isn't an iframe issue. Chrome seems to have something internal that says `chrome://newtab/` means `https://www.google.ca/_/chrome/newtab?espv=2&ie=UTF-8` (or another localized version) and that's what confused Stylish. From the "outside" it's one thing, from the "inside" it's another - no iframes involved.

**Comment by hideheader** [comment]
No, no, NO - now you've just trashed functionality so that the popup is consistent.

**Comment by JasonBarnabe** [comment]
Yes, that's what you're supposed to see - the same list of styles that you would see if you directly navigated to whatever URL Chrome is sending you.

**Comment by hideheader** [comment]
OK, yes, that's good.
