### ISSUE TITLE
Make the branding less obtrusive

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/stylish-chrome#81]
We already know it's Stylish; we clicked the Stylish icon and navigated the Stylish popup to get here, and the Stylish icon is in the tab to remind us if we become confused. Something like the editor page would be better.

![normal](https://cloud.githubusercontent.com/assets/10900909/6787312/56468de2-d168-11e4-8eb8-023e0f5274b5.png)

![maximized](https://cloud.githubusercontent.com/assets/10900909/6787330/66e0a066-d168-11e4-9c65-5ebbc647d907.png)

**Comment by JasonBarnabe** [comment]
I don't mind it too much on the normal-width screen as balances things out. Could be a bit smaller.

On the small-width screen, yeah, it's a little much still.

**Comment by JasonBarnabe** [comment]
Dropped the logo to be consistent with the edit page. https://github.com/JasonBarnabe/stylish-chrome/commit/00d5972cac167ac50c8edaebf5c6748c9e31d466

**Comment by tophf** [comment]
What if someone liked the logo?  

P. S.  Laughed at `_no tophf`.
