### ISSUE TITLE
Code simplification of localization

### ISSUE THREAD

**Issue by tophf** [JasonBarnabe/stylish-chrome#84]
What about I make localization automatically run on html nodes that have:

* `i18n-text="stringID"` attribute for textContent
* `i18n-html="stringID"` attribute for innerHTML
* `any-attribute="i18n:stringID"` for localization of the attribute's value

```html
<html>
	<head>
		<script src="localization.js"></script>
..................................
			<input id="name" class="style-contributor" placeholder="i18n:styleMissingName">
			<button id="cancel-button" i18n-text="styleCancelEditLabel"></button>
			<p id="manage-text" i18n-html="manageText"></p>
```

Is it ok?

**Comment by JasonBarnabe** [comment]
Seems reasonable. I'd rather keep this till after the next release, though.
